"""empty message

Revision ID: 0d677d1fad2c
Revises: cae61c17f3d9
Create Date: 2018-08-03 14:38:19.928901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d677d1fad2c'
down_revision = 'cae61c17f3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('track_length', sa.String(length=254), nullable=True))
    op.add_column('recordings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'recordings', ['track_length'])
    op.create_foreign_key(None, 'recordings', 'account', ['user_id'], ['id'])
    op.drop_column('recordings', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('duration', sa.VARCHAR(length=254), nullable=True))
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_constraint(None, 'recordings', type_='unique')
    op.drop_column('recordings', 'user_id')
    op.drop_column('recordings', 'track_length')
    # ### end Alembic commands ###
